import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from 'next/link'

import Header from '../components/ui/header'
import Home_Container from '../components/home_container'
import Nav from '../components/ui/nav'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Autoholics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Nav/>
      <Home_Container className="mt-20"/>
    </div>
  )
}
